/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        mobile: '100%',
        tablet: '720px',
        desktop: '1140px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          100: '#EAF7EE',
          200: '#C6EDCF',
          300: '#A0E2AE',
          400: '#7BDA8D',
          500: '#56D26C',
          600: '#4AB35C',
          700: '#3A8D45',
          800: '#2C6830',
          900: '#1E421C',
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          100: '#EFF8FC',
          200: '#D8F1FA',
          300: '#B7E8F6',
          400: '#98DFF2',
          500: '#78D6EE',
          600: '#5EB0C8',
          700: '#478695',
          800: '#315A62',
          900: '#1D3335',
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        neutral: {
          white: '#FFFFFF',
          black: '#000000',
          100: '#F9F9F9',
          200: '#EFEFEF',
          300: '#E0E0E0',
          400: '#C8C8C8',
          500: '#A0A0A0',
          600: '#7A7A7A',
          700: '#4E4E4E',
          800: '#2C2C2C',
          900: '#1A1A1A',
        },
        feedback: {
          success: '#28A745',
          info: '#17A2B8',
          warning: '#FFC107',
          error: '#DC3545',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        heading: ['Playfair Display', 'serif'],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1.2' }],
        sm: ['0.875rem', { lineHeight: '1.3' }],
        base: ['1rem', { lineHeight: '1.5' }],
        lg: ['1.125rem', { lineHeight: '1.4' }],
        xl: ['1.5rem', { lineHeight: '1.33' }],
        '2xl': ['2rem', { lineHeight: '1.25' }],
        '3xl': ['2.5rem', { lineHeight: '1.2' }],
        '4xl': ['3rem', { lineHeight: '1.2' }],
      },
      spacing: {
        0: '0px',
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
        20: '80px',
        24: '96px',
        32: '128px',
      },
      borderRadius: {
        none: '0px',
        sm: '4px',
        DEFAULT: '8px',
        md: '8px',
        lg: '16px',
        rounded: '50%',
        pill: '9999px',
      },
      boxShadow: {
        sm: '0px 1px 2px rgba(0,0,0,0.05)',
        DEFAULT: '0px 4px 6px rgba(0,0,0,0.1)',
        md: '0px 4px 6px rgba(0,0,0,0.1)',
        lg: '0px 10px 15px rgba(0,0,0,0.15)',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '300ms',
        slow: '500ms',
      },
      transitionTimingFunction: {
        'ease-in': 'cubic-bezier(0.4, 0.0, 1, 1)',
        'ease-out': 'cubic-bezier(0.0, 0.0, 0.2, 1)',
        'ease-in-out': 'cubic-bezier(0.4, 0.0, 0.2, 1)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        slideUp: {
          from: { transform: 'translateY(20px)', opacity: '0' },
          to: { transform: 'translateY(0)', opacity: '1' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        fadeIn: 'fadeIn 300ms ease-out',
        slideUp: 'slideUp 300ms ease-out',
      },
      screens: {
        mobile: '0px',
        tablet: '768px',
        desktop: '1280px',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

